### ISSUE TITLE
httpd Dockerfile needs work

### ISSUE THREAD

**Issue by miabbott** [scollier/SATraining#43]
As I mentioned in the IRC channel, the example httpd Dockerfile in spcContainers.md needs some help to work when the system has certain subscription.

Additionally, the Docker container doesn't have 'systemctl' to start services...

I suggest adding the following lines to overcome the problem doing 'yum update':

```
RUN yum --disablerepo=\* --enablerepo=rhel-7-server-rpms install -y yum-utils
RUN yum-config-manager --disable \*
RUN yum-config-manager --enable rhel-7-server-rpms
```

**Comment by scollier** [comment]
Thanks.  Yup, that got us further.  The problem is, systemd provides systemctl.  I don't think I should install that in a container.  @rhatdan  Thoughts here?

I'm pushing the change with the updated Dockerfile.

**Comment by rhatdan** [comment]
No we want systemd-container within the image.  It should be there with the RHEL7 image.
We want to show a container running with systemd and jouranld if possible.

Are you sure you were testing with the release RHEL7 base image?

**Comment by scollier** [comment]
@rhatdan Ok, I see what happened.  I copied and pasted your dockerfile.  It references "FROM rhel7", I changed it to registry.access.stage.redhat.com/rhel7:latest

Testing now.  Will update here.

**Comment by miabbott** [comment]
Strange...

If I do a `docker pull rhel7` from the command line, I get what appears to be a rhel7.1 base image from `registry.access.stage.redhat.com`

If I do a `docker build -t httpd .` using the Dockerfile with `FROM rhel7`, I appear to be getting a rhel7.0 base image.

The `rhel7.0` image doesn't appear to have the `systemctl` command, whereas the rhel7.1 image does.

```
# docker images
REPOSITORY                               TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>                                   <none>              eb4d552a154a        12 minutes ago      268.4 MB
registry.access.stage.redhat.com/rhel7   7.1-4               10acc31def5d        3 weeks ago         154.1 MB
registry.access.stage.redhat.com/rhel7   latest              10acc31def5d        3 weeks ago         154.1 MB
rhel7                                    0                   bef54b8f8a2f        8 months ago        139.6 MB
rhel7                                    0-23                bef54b8f8a2f        8 months ago        139.6 MB
rhel7                                    latest              bef54b8f8a2f        8 months ago        139.6 MB
```

**Comment by miabbott** [comment]
I think the last batch of PRs fixes any issues with this.
