### ISSUE TITLE
etcd listens on the localhost only by default

### ISSUE THREAD

**Issue by jlebon** [scollier/SATraining#56]
In the [Flannel tutorial](https://github.com/scollier/SATraining/blob/master/configFlannel.md), it says to PUT the flannel-config.json file using the public IP of the node on which etcd is running. However, etcd listens on the localhost only by default, so this will fail. Of course, this also means that GETing from minions will also fail. To fix this, I had to edit `/etc/etcd/etcd.conf` and change `ETCD_LISTEN_CLIENT_URLS` from `localhost` to `0.0.0.0` to signal etcd to listen on all interfaces. Not sure if there's a better/cleaner way to do it.

This is with `etcd-2.0.9-2.el7.x86_64` on the 7.1.2 tree.

**Comment by scollier** [comment]
fixed. thanks for reporting it @jlebon
